apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-backend-prod
  namespace: portal-app
  labels:
    app: portal-backend-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-backend-prod
  template:
    metadata:
      labels:
        app: portal-backend-prod
    spec:
      containers:
        - name: portal-backend-prod
          image: registry.pdnco.ir/portal-backend:1.0.0
          ports:
            - containerPort: 8090
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: portal-config
                  key: db_url
            - name: SSO_USER
              valueFrom:
                configMapKeyRef:
                  name: portal-config
                  key: sso_user
            - name: SSO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: portal-config
                  key: sso_password
            - name: SSO_APP_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: portal-config
                  key: sso_app_password
            - name: SSO_APP_USER
              valueFrom:
                configMapKeyRef:
                  name: portal-config
                  key: sso_app_user
            - name: SCHEDULER_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: portal-config
                  key: scheduler_db_url
            - name: DLL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: portal-config
                  key: dll_auto
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: portal-db-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portal-db-secret
                  key: db_password
            - name: OAUTH2_JWK_URI
                valueFrom:
                  configMapKeyRef:
                    name: portal-config
                    key: oauth2_jwk_uri



---
apiVersion: v1
kind: Service
metadata:
  name: portal-backend-prod
  namespace: portal-app
  labels:
    name: portal-backend-prod
spec:
  ports:
    - port: 7020
      protocol: TCP
      targetPort: 8090
  selector:
    app: portal-backend-prod